### ISSUE TITLE
TypeError: array_diff_assoc(): Argument #1 ($array) must be of type array, string 

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/redcap-pdf-injector#27]
The 'pdf_injector' module threw the following exception when calling the hook method 'redcap_every_page_top':

```
TypeError: array_diff_assoc(): Argument #1 ($array) must be of type array, string given in /var/www/html/redcap/modules/pdf_injector_v2.2.0/pdfInjector.php:736
Stack trace:
#0 /var/www/html/redcap/modules/pdf_injector_v2.2.0/pdfInjector.php(736): array_diff_assoc()
#1 /var/www/html/redcap/modules/pdf_injector_v2.2.0/pdfInjector.php(547): STPH\pdfInjector\pdfInjector->hasUpdate()
#2 /var/www/html/redcap/modules/pdf_injector_v2.2.0/pdfInjector.php(598): STPH\pdfInjector\pdfInjector->handlePost()
#3 /var/www/html/redcap/modules/pdf_injector_v2.2.0/pdfInjector.php(76): STPH\pdfInjector\pdfInjector->initModule()
#4 /var/www/html/redcap/redcap_v12.4.19/ExternalModules/classes/ExternalModules.php(3229): STPH\pdfInjector\pdfInjector->redcap_every_page_top()
#5 /var/www/html/redcap/redcap_v12.4.19/ExternalModules/classes/ExternalModules.php(3374): ExternalModules\ExternalModules::startHook()
#6 /var/www/html/redcap/redcap_v12.4.19/ExternalModules/classes/ExternalModules.php(3407): ExternalModules\ExternalModules::ExternalModules\{closure}()
#7 /var/www/html/redcap/redcap_v12.4.19/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook()
#8 /var/www/html/redcap/redcap_v12.4.19/Classes/HtmlPage.php(127): Hooks::call()
#9 /var/www/html/redcap/redcap_v12.4.19/Views/HeaderProject.php(32): HtmlPage->PrintHeader()
#10 /var/www/html/redcap/redcap_v12.4.19/ProjectGeneral/header.php(4): require('...')
#11 /var/www/html/redcap/redcap_v12.4.19/ExternalModules/index.php(118): require_once('...')
#12 {main}
```

**Comment by tertek** [comment]
Fixed in 36e80a258b3f603b3d5fc28880da8d16e6886ba7
