### ISSUE TITLE
Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/redcap-pdf-injector#45]
Issue reported by user on REDCap Community:

"I've encountered an error with the module I was hoping you could help with.

The issue occurs when trying to open the injected PDF using the action tag field.
Also, when trying to open the pdf from the record home page nothing happens.

REDCap Version 14.0.33
PDF Injector - v3.1.0

REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in modules\pdf_injector_v3.1.0\pdfInjector.php:314 Stack trace: #0 modules\pdf_injector_v3.1.0\pdfInjector.php(314): array_filter() #1 modules\pdf_injector_v3.1.0\preview.php(13): STPH\pdfInjector\pdfInjector->renderInjection() #2 redcap_v14.0.33\ExternalModules\index.php(146): require('...') #3 {main} thrown
File: modules\pdf_injector_v3.1.0\pdfInjector.php
Line: 314"

Source: 

https://redcap.vumc.org/community/post.php?id=108925&comment=235866

**Comment by tertek** [comment]
Could you please explain what you mean by "using the action tag field" ?

**Comment by tertek** [comment]
Also please report your PHP version.

**Comment by BHDIdata** [comment]
Hello, David here, I will provide as much as I can:

PHP 8.1.3 (Windows OS)

This field when clicking on the button shows the original error:
<html>
<body>

685 | [gp_letter_inject] | Gp Letter Injection Test | descriptiveField Annotation: @PDFI='260472'
-- | -- | -- | --



</body>
</html>

![image](https://github.com/user-attachments/assets/8e241291-0071-4b78-b614-3c3b6a59bb9c)

Clicking on the thumbnail below does not do anything:
![image](https://github.com/user-attachments/assets/f7038744-d435-407f-b461-e9fcdc13ffab)

I have cloned the project and the cloned version works fine, with all pdf injections running, but in the original project (which was created 2023-11-28) it does not work.

**Comment by tertek** [comment]
Hi @BHDIdata 
The error is referring to line 314 where user permissions are being checked:
https://github.com/Research-IT-Swiss-TPH/redcap-pdf-injector/blob/6a249ba24afeb9cc1ad271bfa3721f1455ce4d0c/pdfInjector.php#L312-L314

Could you please compare the user's rights that you encounter the error with, and report back if there is anything different regarding access on that specific project and form?

It is a bug for sure! Thanks :)

**Comment by tertek** [comment]
@BHDIdata The second issue with the thumbnail seems to be a problem in JavaScript. Could you please open the Developer Tools of your browser and check if there are any red messages (errors?)

Please also ensure, that in Module settings the option "Debug" is enabled.

![image](https://github.com/user-attachments/assets/e1d49496-a49b-485d-b578-40bb748ddcf9)

**Comment by BHDIdata** [comment]
Ahh interesting, I realised that my admin account was not actually added to the permissions of the project, since as an admin I rarely need to be. Adding my admin account to the project with permissions has allowed me to access the injected pdf using the action tag button inside the instrument.

However, the javascript button and thumbnail still do not activate

I've refreshed the page and opened the console, this error appears when clicking the button:

![image](https://github.com/user-attachments/assets/308afbcc-4cde-4de3-bb98-943824068a81)

record_home.php?pid=1093&arm=1&id=ELF_001:128  
Uncaught ReferenceError: ELF_001 is not defined
    at HTMLAnchorElement.onclick (record_home.php?pid=1093&arm=1&id=ELF_001:128:220)


In this project, "ELF_001" is the name of the first record, implemented by a module "Custom Record Auto-numbering - v1.0.6" by Luke Stevens (Murdoch Children's Research Institute)
The cloned project does not have this, as I had not thought it necessary for testing, but perhaps that is the cause.

**Comment by tertek** [comment]
@BHDIdata Sorry, this has been delayed for long.
As I can recall from the issue's thread, both issues were tracked down:

Issue A: Uncaught TypeError: Thrown when accessing a project with admin that is not added to project as user. This is caused by Line 312 where `$user_rights[$user_id]["forms"]` will retun `null` as argument to `array_filter`. A fix will be applied, thank you for reporting the issue.

Issue B: It seems that this bug was unrelated to the module, since another module was intercepting the JavaScript execution and may cause the breaking. To be sure I would need more information.

 I will close this issue as soon as Issue A has been fixed. If there is still a problem related to Issue B please feel free to open a new issue.

**Comment by tertek** [comment]
Suggested Fix:

`$user_rights = (array) \REDCap::getUserRights($user_id);`
